# ref: http://docs.travis-ci.com/user/build-configuration

language: cpp

before_install:
    - git submodule update --init --recursive
    - wget "http://www.lua.org/ftp/lua-5.3.4.tar.gz" && tar xzf lua-5.3.4.tar.gz && cd lua-5.3.4 && sudo make linux test install;

install:
    - cd $TRAVIS_BUILD_DIR
    - make bundled

script:
    - make test
